services:
  - type: web
    name: umusomyi-backend
    runtime: image
    image:
      url: bumugisha/umusomyi-backend:latest
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: umusomyi-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: umusomyi-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: umusomyi-db
          property: databaseName
      - key: DB_USER
        fromDatabase:
          name: umusomyi-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: umusomyi-db
          property: password
    plan: free

databases:
  - name: umusomyi-db
    databaseName: umusomyi_wa_bibiliya
    plan: free
